'''Please do not edit this file.'''

import os
import start

# create venv
print("Creating virtual environment...")
os.system(start.sys.executable + " -m venv venv")
# install requirements

print("Installing requirements...")
os.system(start.venv_pip + " install -r requirements.txt")

# run user's setup.py
print("Running user's setup.py...")
start.subprocess.run([start.venv_python, "src/_setup.py"])

print("pakenv setup complete.")