'''Please do not edit this file.'''

import sys
import subprocess

venv_python:str = "venv\\Scripts\\python.exe" if sys.platform == "win32" else "venv/bin/python"
venv_pip:str = "venv\\Scripts\\pip.exe" if sys.platform == "win32" else "venv/bin/pip"

if __name__ == "__main__":

	subprocess.run([venv_python, "src/main.py"])